name: Notify Telegram on Push

on:
  push:
    branches:
      - main  # Chỉ gửi thông báo khi có commit lên nhánh main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="📢 *GitHub Repo Update!*\n\n🔹 Repository: \`${{ github.repository }}\`\n🛠 Pushed by: \`${{ github.actor }}\`\n📄 Commit Message: \`${{ github.event.head_commit.message }}\`\n🔗 [View Commit](${{ github.event.head_commit.url }})"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"
